### ISSUE TITLE
Tarea semana 2 finalizada

### ISSUE THREAD

**Issue by JoseRaulVera** [interfacesweb-19-20/guia-estilos-JoseRaulVera#1]
Hola @pedroprieto . Ya está finalizada la tarea de la segunda semana.
Saludos.
Raul.

**Comment by pedroprieto** [comment]
Hola Raúl,

Está bastante bien. Te he comentado unos problemas con los nombres de archivo (mayúsculas). También echo en falta algo más de contraste entre los colores: no se distingue demasiado bien el color principal (enlaces) del color de fondo.

Bonito logo, por cierto!!

Todo lo que se pedía de la práctica está, pese a los errores (ne esta práctica todavía no voy a evaluar el código), así que tienes un 10!. Enhorabuena! :+1:
